backend:
  name: git-gateway
  branch: main
  identity_url: "https://dulcet-malabi-84f14c.netlify.app/.netlify/identity"
  gateway_url: "https://dulcet-malabi-84f14c.netlify.app/.netlify/git"
  accept_roles: ["admin"]  # seuls les comptes avec rôle "admin" auront accès


media_folder: "assets/img/uploads"
public_folder: "/assets/img/uploads"

publish_mode: editorial_workflow

collections:
  - name: "pages"
    label: "Pages principales"
    files:
      - file: "index.html"
        label: "Accueil"
        name: "index"
        fields:
          - {label: "Titre principal", name: "hero_title", widget: "string", required: false}
          - {label: "Sous-titre", name: "hero_subtitle", widget: "text", required: false}
      - file: "tarifs.html"
        label: "Tarifs"
        name: "tarifs"
        fields:
          - {label: "Texte intro", name: "pricing_intro", widget: "text", required: false}
      - file: "evenements.html"
        label: "Événements"
        name: "evenements"
        fields:
          - {label: "Texte intro", name: "events_intro", widget: "text", required: false}
      - file: "contact.html"
        label: "Contact"
        name: "contact"
        fields:
          - {label: "Téléphone", name: "phone", widget: "string", default: "06 72 39 22 64"}
          - {label: "Email", name: "email", widget: "string", default: "contact@lgbl-experience.fr"}

  - name: "annonces"
    label: "Annonces (Accueil)"
    folder: "content/annonces"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    extension: "md"
    fields:
      - {label: "Titre", name: "title", widget: "string"}
      - {label: "Date", name: "date", widget: "datetime"}
      - {label: "Contenu", name: "body", widget: "markdown"}
